apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
    template:
      metadata:
        labels:
          app: chat
      spec:
        containers:
          - name: chat
            image: glichfalls/chat:latest
            ports:
              - containerPort: 5000